### ISSUE TITLE
Spurious failure in test_rm

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#689]
Test_rm.py:test_binary is failing; this combination of dependencies is currently excluded from the CI matrix so it is very urgent to get this fixed and remove it from exclusions.

**Comment by bpablo** [comment]
I am unable to get this branch to install. Here is the install information.

python setup.py install --user
/Users/bertpablo/repos/phoebe2/setup.py:14: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.core import setup, Extension
/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running config_cc
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
INFO: build_src
INFO: building extension "libphoebe" sources
INFO: building extension "phoebe.algorithms.ceclipse" sources
INFO: build_src: building npy-pkg config files
running build_py
running build_ext
INFO: customize UnixCCompiler
INFO: customize UnixCCompiler using build_check
INFO: CCompilerOpt.__init__[813] : load cache from file -> /Users/bertpablo/repos/phoebe2/build/temp.macosx-10.9-universal2-cpython-311/ccompiler_opt_cache_ext.py
INFO: CCompilerOpt.__init__[824] : hit the file cache
INFO: customize UnixCCompiler
WARN: #### ['clang', '-Wsign-compare', '-Wunreachable-code', '-fno-common', '-dynamic', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-arch', 'arm64', '-arch', 'x86_64', '-g'] #######
INFO: customize UnixCCompiler using build_check
OS: Darwin
OS version: 21.6.0
Compiler: clang++
Compiler version: Apple clang version 14.0.0 (clang-1400.0.29.202)
/Users/bertpablo/repos/phoebe2/setup.py:105: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(plat_ver) < LooseVersion("13.0"): #OS X Mavericks
/Users/bertpablo/repos/phoebe2/setup.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  version_ok = LooseVersion(ver[1]) >= LooseVersion("3.3")
Ready to compile with clang ('clang', '14.0.0').
Compiler: clang
Compiler version: Apple clang version 14.0.0 (clang-1400.0.29.202)
Ready to compile with clang ('clang', '14.0.0').
  extra_args=['-std=c++11']
  extra_args=[]
INFO: building 'libphoebe' extension
INFO: compiling C++ sources
INFO: C compiler: clang++ -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -ftrapping-math

INFO: compile options: '-I/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/numpy/core/include -I/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-universal2-3.11/numpy/distutils/include -I/Users/bertpablo/phoebe-test/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c'
extra options: '-std=c++11'
INFO: clang++: phoebe/lib/libphoebe.cpp
warning: overriding currently unsupported use of floating point exceptions on this target [-Wunsupported-floating-point-opt]
In file included from phoebe/lib/libphoebe.cpp:42:
In file included from phoebe/lib/utils.h:15:
phoebe/lib/sincos.h:44:30: error: invalid output constraint '=t' in asm
    asm volatile("fsincos" : "=t" (*c), "=u" (*s) : "0" (angle));
                             ^
phoebe/lib/sincos.h:44:30: error: invalid output constraint '=t' in asm
phoebe/lib/clipper.h:4869:10: note: in instantiation of function template specialization 'utils::sincos<double>' requested here
  utils::sincos(two_pi/steps, &m_sin, &m_cos);
         ^
In file included from phoebe/lib/libphoebe.cpp:42:
In file included from phoebe/lib/utils.h:15:
phoebe/lib/sincos.h:44:30: error: invalid output constraint '=t' in asm
    asm volatile("fsincos" : "=t" (*c), "=u" (*s) : "0" (angle));
                             ^
phoebe/lib/misaligned_roche.h:1322:14: note: in instantiation of function template specialization 'utils::sincos<long double>' requested here
      utils::sincos(real(th), sc_nu, sc_nu+1);
             ^
phoebe/lib/misaligned_roche.h:1987:5: note: in instantiation of function template specialization 'misaligned_roche::critical_area_volume_integration<double>' requested here
    critical_area_volume_integration(av, choice, x, q, F, d, th1, 1<<10);
    ^
phoebe/lib/libphoebe.cpp:2009:26: note: in instantiation of function template specialization 'misaligned_roche::critical_area_volume<double>' requested here
  if (!misaligned_roche::critical_area_volume(2, q, F, d, theta, OmegaC, buf)){
                         ^
1 warning and 3 errors generated.
error: Command "clang++ -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -ftrapping-math -I/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/numpy/core/include -I/Users/bertpablo/phoebe-test/lib/python3.11/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-universal2-3.11/numpy/distutils/include -I/Users/bertpablo/phoebe-test/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c phoebe/lib/libphoebe.cpp -o build/temp.macosx-10.9-universal2-cpython-311/phoebe/lib/libphoebe.o -MMD -MF build/temp.macosx-10.9-universal2-cpython-311/phoebe/lib/libphoebe.o.d -std=c++11" failed with exit status 1
INFO: 
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      : 
  Architecture: unsupported
  Compiler    : clang

CPU baseline  : 
  Requested   : optimization disabled
  Enabled     : none
  Flags       : none
  Extra checks: none
  Requested   : optimization disabled

CPU dispatch  : 
  Enabled     : none
  Generated   : none
INFO: CCompilerOpt.cache_flush[857] : write cache to path -> /Users/bertpablo/repos/phoebe2/build/temp.macosx-10.9-universal2-cpython-311/ccompiler_opt_cache_ext.py

**Comment by bpablo** [comment]
The test is failing because the assertion is not within specified parameters atol=2.0 where as:

rv@primary max abs diff: 0.01235466329377033
rv@secondary max abs diff: 3.041610244695378
whereas atol =2.0
Note this only happens with syncpar=0.25. syncpar =4.0 runs as expected
Traceback (most recent call last):
  File "/Users/bertpablo/repos/phoebe2/tests/nosetests/test_rm/test_rm.py", line 60, in <module>
    b = test_binary(plot=True, gen_comp=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bertpablo/repos/phoebe2/tests/nosetests/test_rm/test_rm.py", line 53, in test_binary
    _beta_vs_legacy(b, syncpar, plot=plot, gen_comp=gen_comp)
  File "/Users/bertpablo/repos/phoebe2/tests/nosetests/test_rm/test_rm.py", line 33, in _beta_vs_legacy
    assert(np.allclose(phoebe2_val, phoebe1_val, rtol=0., atol=2.0))
AssertionError

**Comment by aprsa** [comment]
that's not good; I'm getting:
```
rv@primary max abs diff: 0.05914204480890817
rv@secondary max abs diff: 0.03824515954376752
```
We'll need to dig deeper to find the source of the discrepancy between this build and all others.

**Comment by kecnry** [comment]
One nice thing about having used the exported file is that we also now know that the results are changing on the phoebe-side (and legacy can't be completely to blame, at least).

**Comment by kecnry** [comment]
I think our next step is to write a test with assertions for the outputs from the [distortions.roche functions](https://github.com/phoebe-project/phoebe2/blob/master/phoebe/distortions/roche.py) which wrap libphoebe for the asynchronous cases and try to track down if one of those is behaving differently.

**Comment by aprsa** [comment]
@bpablo, any luck with this? I'd do it but, without a mac to test it on, it's difficult. @horvatm, do you think you could write a small test suite for the functions Kyle suggests above to help us track down this issue?

**Comment by aprsa** [comment]
As always, once you figure it out, it's dead obvious what was causing it. See the corresponding [pull request](https://github.com/phoebe-project/phoebe2/pull/787).

**Comment by horvatm** [comment]
It this a legit way to fix this? There are two issues: 

1. That at conjunction there are exceptionally large numerical fluctuations on any machine
2. That on arm based machines these numerical fluctuations are even bigger.

Basically, what you did in the fix is to avoid testing the problem. I am wrong?

**Comment by aprsa** [comment]
The test - as it was - made no practical sense because the accuracy of the horizon determination in legacy is way lower than the effect we were testing here. The numerical artifacts in this case are entirely expected and I would not be losing sleep over them. If such a circumstance indeed needs to be synthesized, the number of triangles needs to be increased adequately.
